
adjective1 = input("Enter a adjective: ")
adjective2 = input("Enter a adjective: ")
bird = input("Enter a type of bird: ")
room = input("Enter a room in the house: ")
ptverb = input("Enter a past tense verb: ")
verb = input("Enter a verb: ")
relative = input("Enter a relative's name: ")
noun1 = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
verbing1 = input("Enter a verb ending with -ing: ")
body = input("Enter a plural part of the body: ")
plnoun = input("Enter a plural noun: ")
verbing2 = input("Enter a verb ending with -ing: ")
noun2 = input("Enter a noun: ")

print("It was a " + adjective1 + " cold November day.")
print("I woke up to the " + adjective2 + " smell of " + bird + " roasting in the " + room + " downstairs.")
print("I " + ptverb + " down the stairs to see if I could help" + verb + " the dinner.")
print("My mom said, 'See if " + relative + " needs a fresh" + noun1 + ".'")
print("So I carried a tray of glasses full of " + liquid + " into the " + verbing1 + " room.")
print("When I got there, I couldn't believe my" + body + "!")
print("There were " + plnoun + " " + verbing2 + " on the " + noun2 + "!")